languageCode = "en-us"
title = "saptak.in"
canonifyurls = false
baseurl = "http://saptak.in"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  	Description = "saptak.in"
  	author = "Saptak Sen"
	twitter = "saptak"
	github = "saptak"
